//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Raccoon.Ninja.ValidatorDotNet.Internationalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Raccoon.Ninja.ValidatorDotNet.Internationalization.ValidationErrorMessages", typeof(ValidationErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; has a DateTime value of &apos;{1}&apos;, but it is not in UTC.
        /// </summary>
        public static string DateTimeNotInUTC {
            get {
                return ResourceManager.GetString("DateTimeNotInUTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; of {1} is missing.
        /// </summary>
        public static string DynamicPropMissing {
            get {
                return ResourceManager.GetString("DynamicPropMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found in the parameter &apos;{0}&apos;.
        /// </summary>
        public static string EmptyList {
            get {
                return ResourceManager.GetString("EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list in parameter &apos;{0}&apos; contains invalid {1} enums.
        /// </summary>
        public static string InvalidEnumList {
            get {
                return ResourceManager.GetString("InvalidEnumList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; has a value of &apos;{1}&apos; but it is not a valid enum of type &apos;{2}&apos;.
        /// </summary>
        public static string InvalidEnumValue {
            get {
                return ResourceManager.GetString("InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid that identifies {0} is empty or invalid.
        /// </summary>
        public static string InvalidGuid {
            get {
                return ResourceManager.GetString("InvalidGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;{0}&apos; has a invalid utcoffset value of &apos;{1}&apos;. It must be between &apos;{2}&apos; and &apos;{3}&apos;.
        /// </summary>
        public static string InvalidUtcValue {
            get {
                return ResourceManager.GetString("InvalidUtcValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING! Found &apos;{0}&apos; affected rows of type {1} with id {2}.
        /// </summary>
        public static string MultiRowsAffectedById {
            get {
                return ResourceManager.GetString("MultiRowsAffectedById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No entry of type &apos;{0}&apos; found with id &apos;{1}&apos;.
        /// </summary>
        public static string NoEntryWithId {
            get {
                return ResourceManager.GetString("NoEntryWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all numbers in the list &apos;{0}&apos; are positive.
        /// </summary>
        public static string NotAllNumbersArePositive {
            get {
                return ResourceManager.GetString("NotAllNumbersArePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting parameter &apos;{0}&apos; to have a value of &apos;{1}&apos;, but got &apos;{2}&apos; instead.
        /// </summary>
        public static string NotEqualTo {
            get {
                return ResourceManager.GetString("NotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting a value greather than &apos;{0}&apos; for parameter &apos;{1}&apos;, but got  &apos;{2}&apos; instead.
        /// </summary>
        public static string NotGreaterThan {
            get {
                return ResourceManager.GetString("NotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting a value greather than or equal to &apos;{0}&apos; for parameter &apos;{1}&apos;, but got &apos;{2}&apos; instead.
        /// </summary>
        public static string NotGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("NotGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting a value lesser than &apos;{0}&apos; for parameter &apos;{1}&apos;, but got  &apos;{2}&apos; instead.
        /// </summary>
        public static string NotLessThan {
            get {
                return ResourceManager.GetString("NotLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting a value lesser than or equal to &apos;{0}&apos; for parameter &apos;{1}&apos;, but got  &apos;{2}&apos; instead.
        /// </summary>
        public static string NotLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("NotLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} is required and cannot be null/empty.
        /// </summary>
        public static string NullRequiredValue {
            get {
                return ResourceManager.GetString("NullRequiredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string &apos;{0}&apos; cannot be converted to number.
        /// </summary>
        public static string StringIsNotANumber {
            get {
                return ResourceManager.GetString("StringIsNotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of {0} exceeded {1} characters.
        /// </summary>
        public static string TextSizeExceededMaxChars {
            get {
                return ResourceManager.GetString("TextSizeExceededMaxChars", resourceCulture);
            }
        }
    }
}
